main: com.artemis.the.gr8.playerstats.core.Main
name: PlayerStats
version: 2.4
api-version: 1.13
description: adds commands to view player statistics in chat
author: Artemis_the_gr8
folia-supported: true
softdepend:
  - PlaceholderAPI
commands:
  statistic:
    aliases:
      - stat
      - stats
    description: show player statistics in private chat
    usage: "ยง6/stat info"
    permission: playerstats.stat
  statisticshare:
    aliases:
      - statshare
      - statsshare
    description: share last stat lookup in chat
    usage: "ยง6/This command can only be executed by clicking the \"share\" button in /stat results. 
    If you don't see this button, you don't have share-permission, or sharing is turned off."
    permission: playerstats.share
  statisticreload:
    aliases:
      - statreload
      - statsreload
    description: reloads the config
    usage: "ยง6/statreload"
    permission: playerstats.reload
  statisticexclude:
    aliases:
      - statexclude
      - statsexclude
    description: hide this player's statistics from /stat results
    usage: "ยง6/statexclude info"
    permission: playerstats.exclude
permissions:
  playerstats.stat:
    description: allows usage of /statistic
    default: true
  playerstats.share:
    description: allows sharing stats in chat
    default: true
  playerstats.exclude:
    description: allows usage of /statexclude
    default: op
  playerstats.reload:
    description: allows usage of /statreload
    default: op